# Generated by Django 4.2.20 on 2025-03-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=7),
        ),
    ]
